import { Service, Testimonial, ProcessStep, FAQItem, Project } from './types';

export const COMPANY_INFO = {
  name: 'SP2C Plomberie Chauffage Climatisation',
  shortName: 'SP2C',
  phone: '+33 6 25 07 56 40',
  phoneDisplay: '06 25 07 56 40',
  email: 'contact@sp2c-plomberie-arles.fr',
  address: {
    street: 'Arles',
    city: 'Arles',
    postalCode: '13200',
    region: 'Bouches-du-Rhône',
    country: 'France',
  },
  yearFounded: 2015,
  siret: '123 456 789 00012',
  coordinates: {
    lat: 43.6772,
    lng: 4.6309,
  },
  openingHours: [
    { days: 'Lundi - Vendredi', hours: '8h00 - 18h00' },
    { days: 'Samedi', hours: '9h00 - 12h00' },
    { days: 'Dimanche', hours: 'Fermé' },
  ],
  socialMedia: {
    facebook: '#',
    instagram: '#',
    linkedin: '#',
  },
};

export const SERVICES: Service[] = [
  {
    id: '1',
    slug: 'installation-reparation-robinetterie',
    title: 'Installation & Réparation de Robinetterie',
    shortDescription: 'Pose et réparation de tous types de robinets. Intervention rapide sur Arles et environs.',
    fullDescription: 'Notre équipe d\'experts intervient pour l\'installation et la réparation de tous types de robinetterie : robinets de cuisine, salle de bain, douche, baignoire. Nous travaillons avec des marques de qualité et garantissons un travail soigné.',
    icon: 'Droplet',
    benefits: [
      'Intervention sous 24h',
      'Garantie pièces et main d\'œuvre 2 ans',
      'Conseils personnalisés sur le choix',
    ],
    priceRange: '80€ - 350€',
    imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80',
    featured: true,
  },
  {
    id: '2',
    slug: 'detection-reparation-fuites',
    title: 'Détection & Réparation de Fuites',
    shortDescription: 'Détection précise et réparation rapide de toutes fuites d\'eau, sans casse inutile.',
    fullDescription: 'Nous utilisons des équipements de pointe pour détecter les fuites cachées (caméra thermique, détecteur acoustique). Réparation rapide pour éviter les dégâts des eaux et réduire votre facture.',
    icon: 'AlertTriangle',
    benefits: [
      'Détection sans destruction',
      'Intervention d\'urgence 7j/7',
      'Rapport détaillé pour assurance',
    ],
    priceRange: '120€ - 500€',
    imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&q=80',
    featured: true,
  },
  {
    id: '3',
    slug: 'installation-reparation-chauffe-eau',
    title: 'Installation & Réparation Chauffe-Eau',
    shortDescription: 'Installation et dépannage de chauffe-eau électrique, gaz et thermodynamique.',
    fullDescription: 'Spécialistes en chauffe-eau depuis plus de 10 ans. Installation neuve, remplacement, entretien et réparation de tous types de chauffe-eau. Conseil sur le dimensionnement adapté à vos besoins.',
    icon: 'Flame',
    benefits: [
      'Conseils sur le modèle optimal',
      'Installation en une journée',
      'Entretien et maintenance',
    ],
    priceRange: '450€ - 2500€',
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80',
    featured: true,
  },
  {
    id: '4',
    slug: 'installation-renovation-salle-bain',
    title: 'Installation & Rénovation Salle de Bain',
    shortDescription: 'Création et rénovation complète de salles de bain modernes et fonctionnelles.',
    fullDescription: 'De la conception à la réalisation, nous prenons en charge votre projet de A à Z : plomberie, carrelage, électricité, menuiserie. Des salles de bain sur-mesure qui allient esthétique et praticité.',
    icon: 'Bath',
    benefits: [
      'Projet clé en main',
      'Visualisation 3D du projet',
      'Suivi de chantier personnalisé',
    ],
    priceRange: '3500€ - 15000€',
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    featured: true,
  },
  {
    id: '5',
    slug: 'installation-reparation-douche',
    title: 'Installation & Réparation de Douches',
    shortDescription: 'Pose de douches italiennes, cabines et colonnes de douche. Réparation tous modèles.',
    fullDescription: 'Installation de douches à l\'italienne, cabines de douche, colonnes hydromassantes. Réparation de fuites, remplacement de joints, mitigeurs et pommeaux.',
    icon: 'Shower',
    benefits: [
      'Large choix de modèles',
      'Étanchéité garantie 10 ans',
      'Installation en 1 à 2 jours',
    ],
    priceRange: '800€ - 4500€',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    featured: false,
  },
  {
    id: '6',
    slug: 'installation-reparation-toilettes',
    title: 'Installation & Réparation de Toilettes',
    shortDescription: 'Pose et dépannage de WC classiques, suspendus et japonais.',
    fullDescription: 'Installation de toilettes neuves (WC classique, suspendu, avec broyeur). Réparation de fuites, mécanismes de chasse d\'eau, débouchage.',
    icon: 'Square',
    benefits: [
      'Choix varié de modèles',
      'Installation propre et rapide',
      'Dépannage sous 24h',
    ],
    priceRange: '250€ - 1800€',
    imageUrl: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
    featured: false,
  },
  {
    id: '7',
    slug: 'debouchage-canalisation',
    title: 'Débouchage de Canalisations',
    shortDescription: 'Débouchage professionnel de tous types de canalisations. Intervention rapide.',
    fullDescription: 'Débouchage de canalisations bouchées (évier, lavabo, douche, WC, égouts). Utilisation de techniques adaptées : furet, haute pression, inspection caméra.',
    icon: 'Waves',
    benefits: [
      'Intervention d\'urgence possible',
      'Inspection vidéo gratuite',
      'Garantie de débouchage',
    ],
    priceRange: '90€ - 350€',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
    featured: true,
  },
  {
    id: '8',
    slug: 'plomberie-piscine',
    title: 'Plomberie de Piscine',
    shortDescription: 'Installation et réparation de systèmes de plomberie pour piscines.',
    fullDescription: 'Spécialistes de la plomberie de piscine : installation de filtration, pompes, chauffage, traitement automatique. Réparation de fuites, remplacement de pièces défectueuses.',
    icon: 'Droplets',
    benefits: [
      'Expertise piscine depuis 10 ans',
      'Matériel professionnel',
      'Conseil en économies d\'eau et d\'énergie',
    ],
    priceRange: '300€ - 3500€',
    imageUrl: 'https://images.unsplash.com/photo-1600490889607-e9a9a1b8e23d?w=800&q=80',
    featured: false,
  },
  {
    id: '9',
    slug: 'installation-adoucisseur-eau',
    title: 'Installation d\'Adoucisseur d\'Eau',
    shortDescription: 'Pose d\'adoucisseurs pour une eau de qualité et protéger vos installations.',
    fullDescription: 'Installation d\'adoucisseurs d\'eau pour lutter contre le calcaire, prolonger la durée de vie de vos équipements et améliorer votre confort. Entretien et fourniture de sel.',
    icon: 'Filter',
    benefits: [
      'Économies sur l\'entretien',
      'Peau et cheveux protégés',
      'Installation en demi-journée',
    ],
    priceRange: '800€ - 2200€',
    imageUrl: 'https://images.unsplash.com/photo-1597047084897-51e81819a499?w=800&q=80',
    featured: false,
  },
  {
    id: '10',
    slug: 'nettoyage-gouttiere',
    title: 'Nettoyage de Gouttières',
    shortDescription: 'Nettoyage et entretien de gouttières pour éviter les infiltrations.',
    fullDescription: 'Nettoyage complet de vos gouttières et chéneaux. Vérification de l\'écoulement, détection de fuites, réparations mineures. Service régulier ou ponctuel.',
    icon: 'CloudRain',
    benefits: [
      'Prévention des infiltrations',
      'Contrôle gratuit des descentes',
      'Forfaits annuels disponibles',
    ],
    priceRange: '80€ - 250€',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    featured: false,
  },
  {
    id: '11',
    slug: 'depannage-urgence-plomberie',
    title: 'Dépannage Urgence Plomberie',
    shortDescription: 'Service d\'urgence 7j/7 pour tous vos problèmes de plomberie.',
    fullDescription: 'Notre équipe est disponible 7j/7 pour les urgences plomberie : fuites importantes, dégâts des eaux, chaudière en panne, WC bouchés. Intervention rapide sur Arles et 30km autour.',
    icon: 'Siren',
    benefits: [
      'Disponible 24h/24, 7j/7',
      'Intervention en moins de 2h',
      'Devis gratuit sur place',
    ],
    priceRange: '120€ - 600€',
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80',
    featured: true,
  },
  {
    id: '12',
    slug: 'renovation-plomberie-complete',
    title: 'Rénovation Plomberie Complète',
    shortDescription: 'Rénovation totale de plomberie pour maisons anciennes et rénovations lourdes.',
    fullDescription: 'Rénovation complète de votre installation de plomberie : remplacement des canalisations, mise aux normes, optimisation du réseau. Idéal pour maisons anciennes ou projets de rénovation.',
    icon: 'Wrench',
    benefits: [
      'Mise aux normes garantie',
      'Étude technique préalable',
      'Garantie décennale',
    ],
    priceRange: '4000€ - 18000€',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
    featured: false,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Marie Dupont',
    location: 'Arles Centre',
    rating: 5,
    text: 'Intervention rapide pour une fuite sous mon évier. Le plombier était très professionnel, a trouvé le problème en 10 minutes et réparé en 30 minutes. Prix honnête et travail impeccable. Je recommande vivement SP2C !',
    service: 'Détection & Réparation de Fuites',
    date: '2024-03',
  },
  {
    id: '2',
    name: 'Jean-Pierre Martin',
    location: 'Fontvieille',
    rating: 5,
    text: 'Rénovation complète de ma salle de bain. Le résultat dépasse mes attentes ! L\'équipe a été à l\'écoute de mes besoins, les finitions sont parfaites. Chantier propre et respectueux des délais annoncés.',
    service: 'Rénovation Salle de Bain',
    date: '2024-02',
  },
  {
    id: '3',
    name: 'Sophie Lefebvre',
    location: 'Arles',
    rating: 5,
    text: 'Installation d\'un nouveau chauffe-eau thermodynamique. Excellent conseil sur le modèle à choisir, installation soignée en une journée. Depuis 6 mois, aucun problème et une vraie économie sur ma facture électrique.',
    service: 'Installation Chauffe-Eau',
    date: '2024-01',
  },
  {
    id: '4',
    name: 'Patrick Rousseau',
    location: 'Saint-Martin-de-Crau',
    rating: 5,
    text: 'Dépannage d\'urgence un dimanche pour une fuite importante. Arrivée en moins d\'une heure, diagnostic rapide et réparation efficace. Un grand merci pour votre réactivité et votre professionnalisme.',
    service: 'Dépannage Urgence',
    date: '2024-02',
  },
  {
    id: '5',
    name: 'Isabelle Bernard',
    location: 'Tarascon',
    rating: 5,
    text: 'Installation d\'une douche à l\'italienne et réfection de la plomberie. Travail de qualité, bons conseils et respect du budget. L\'équipe est sérieuse et compétente. Je ferai à nouveau appel à eux.',
    service: 'Installation Douche',
    date: '2024-03',
  },
  {
    id: '6',
    name: 'Marc Dubois',
    location: 'Arles',
    rating: 5,
    text: 'Débouchage de canalisation avec inspection vidéo. Très satisfait du service : rapide, efficace et prix correct. Le technicien m\'a expliqué le problème et donné des conseils pour l\'éviter à l\'avenir.',
    service: 'Débouchage',
    date: '2024-03',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: 1,
    title: 'Contact & Diagnostic',
    description: 'Vous nous contactez par téléphone ou via notre formulaire. Nous analysons votre besoin et planifions une visite si nécessaire.',
    icon: 'Phone',
  },
  {
    number: 2,
    title: 'Devis Gratuit & Détaillé',
    description: 'Nous établissons un devis clair et détaillé sous 48h maximum. Pas de frais cachés, tout est transparent.',
    icon: 'FileText',
  },
  {
    number: 3,
    title: 'Intervention Planifiée',
    description: 'Nous convenons ensemble d\'une date d\'intervention adaptée à votre emploi du temps. Ponctualité garantie.',
    icon: 'Calendar',
  },
  {
    number: 4,
    title: 'Travaux & Suivi Qualité',
    description: 'Nos techniciens certifiés réalisent les travaux dans le respect des normes. Chantier propre et soigné.',
    icon: 'CheckCircle2',
  },
  {
    number: 5,
    title: 'Garantie & SAV',
    description: 'Tous nos travaux sont garantis. Notre service après-vente reste à votre écoute pour toute question.',
    icon: 'Shield',
  },
];

export const FAQ: FAQItem[] = [
  {
    question: 'Intervenez-vous en urgence le week-end et les jours fériés ?',
    answer: 'Oui, notre service d\'urgence est disponible 7j/7, y compris les week-ends et jours fériés. Pour les urgences (fuites importantes, dégâts des eaux), nous intervenons dans les 2 heures sur Arles et les communes environnantes (rayon de 30km).',
  },
  {
    question: 'Quel est le délai pour obtenir un devis ?',
    answer: 'Pour les petits travaux, nous pouvons établir un devis par téléphone immédiatement. Pour les projets plus importants (rénovation de salle de bain, installation complète), nous effectuons une visite gratuite à votre domicile et vous remettons un devis détaillé sous 48h maximum.',
  },
  {
    question: 'Quelles sont vos zones d\'intervention ?',
    answer: 'Nous intervenons principalement sur Arles et les communes environnantes : Fontvieille, Tarascon, Saint-Martin-de-Crau, Fourques, Bellegarde, dans un rayon de 30km autour d\'Arles. Pour les interventions hors zone, contactez-nous pour étudier votre demande.',
  },
  {
    question: 'Proposez-vous des facilités de paiement ?',
    answer: 'Oui, pour les chantiers importants (plus de 2000€), nous proposons des facilités de paiement en 2, 3 ou 4 fois sans frais. Nous acceptons les paiements par chèque, virement bancaire et carte bancaire. Un acompte de 30% est demandé au démarrage des travaux.',
  },
  {
    question: 'Vos travaux sont-ils garantis ?',
    answer: 'Absolument. Tous nos travaux sont garantis : garantie décennale pour les gros travaux, garantie de 2 ans sur les pièces et main d\'œuvre pour les installations et réparations. Nous sommes assurés en responsabilité civile professionnelle et décennale.',
  },
  {
    question: 'Faut-il être présent pendant l\'intervention ?',
    answer: 'Pour un diagnostic initial et la remise du devis, votre présence est préférable. Pour les travaux, si vous nous faites confiance, nous pouvons intervenir en votre absence (avec accès sécurisé). Nous vous tenons informé de l\'avancement par SMS/téléphone et faisons un point détaillé à la fin de l\'intervention.',
  },
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Rénovation Salle de Bain Complète',
    service: 'Rénovation',
    location: 'Arles Centre',
    beforeImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    description: 'Transformation totale d\'une salle de bain des années 80 en espace moderne avec douche à l\'italienne.',
    metric: '+45% de luminosité',
  },
  {
    id: '2',
    title: 'Installation Chauffe-Eau Thermodynamique',
    service: 'Chauffage',
    location: 'Fontvieille',
    beforeImage: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80',
    description: 'Remplacement d\'un vieux ballon électrique par un chauffe-eau thermodynamique haute performance.',
    metric: '-60% sur la facture',
  },
  {
    id: '3',
    title: 'Création Douche Italienne PMR',
    service: 'Douche',
    location: 'Tarascon',
    beforeImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
    description: 'Installation d\'une douche à l\'italienne adaptée PMR avec siège et barres d\'appui.',
    metric: '100% accessible',
  },
  {
    id: '4',
    title: 'Rénovation Plomberie Maison Ancienne',
    service: 'Rénovation',
    location: 'Arles',
    beforeImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80',
    description: 'Rénovation complète de la plomberie d\'une maison des années 60 avec mise aux normes.',
    metric: '0 fuite garantie',
  },
];

export const MENU_ITEMS = [
  { label: 'Accueil', href: '/' },
  { label: 'Nos Services', href: '/nos-services' },
  { label: 'Réalisations', href: '/realisations' },
  { label: 'Contact', href: '/contact' },
];

export const STATS = [
  { number: 850, label: 'Projets Réalisés', suffix: '+', icon: 'CheckCircle2' },
  { number: 10, label: 'Années d\'Expérience', suffix: '', icon: 'Award' },
  { number: 98, label: 'Clients Satisfaits', suffix: '%', icon: 'Star' },
  { number: 48, label: 'Délai Devis', suffix: 'h', icon: 'Clock' },
];
